# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=8)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_type', models.IntegerField(choices=[(0, 'Contract'), (1, 'Cooperative Agreement'), (2, 'Donation/Gift'), (3, 'Grant'), (4, 'Fellowship')], default=3)),
                ('funding_source', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128, verbose_name='Award name')),
                ('short_name', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=64, verbose_name='Award number')),
                ('dept_id', models.CharField(max_length=7, verbose_name='Dept ID')),
                ('grant_code', models.CharField(blank=True, max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('abstract', models.TextField(blank=True)),
                ('awarded_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Funding',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_title', models.IntegerField(choices=[(4, 'Director'), (3, 'Manager'), (2, 'Chair'), (1, 'Principal Investigator'), (5, 'Principal')], default=1)),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', to='institutions.Department')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_name', models.CharField(max_length=16)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=8)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='program',
            field=models.ManyToManyField(to='institutions.Program'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.Institution'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='program',
            order_with_respect_to='institution',
        ),
        migrations.AlterOrderWithRespectTo(
            name='institution',
            order_with_respect_to='parent',
        ),
        migrations.AlterOrderWithRespectTo(
            name='department',
            order_with_respect_to='institution',
        ),
    ]
