# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('start_year', models.PositiveIntegerField(blank=True, choices=[(1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, choices=[(1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], null=True)),
                ('current_position', models.TextField(blank=True, help_text='A simple job/position title for current members of the lab. For lab alumni, please include company/institution/organization information along with job title.', null=True)),
                ('date_added', models.DateField(auto_now_add=True, help_text='The date this person was added to the database.')),
                ('last_updated', models.DateField(blank=True, help_text="The date this person's information was last updated.", null=True)),
                ('email_address', models.EmailField(blank=True, help_text='Primary e-mail address for this lab member. For current Tufts affiliates, please enter their Tufts e-mail address here.', max_length=254, null=True, unique=True)),
                ('email_address_alt', models.EmailField(blank=True, help_text='An alternate e-mail address for this lab member, in case the primary becomes deactivated.', max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraineeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('abbreviation', models.CharField(max_length=24)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='labmember',
            name='trainee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_members.TraineeType'),
        ),
    ]
